### PR TITLE
Add location to item name

### PR DESCRIPTION
**Pull request by donal-s**
Adds the item store location to the item summary in the container and missing list views, 
e.g: "Sterile gloves (Small) - Resus store XX"

### CODE REVIEW

**Comment by byronn-1** [comment]
Looks good, I haven't had chance to run locally and deploy the test suites. I will endeavour to do this, this evening. 
Only one question I presume the logic for not rendering missing fields was already in place?

**Comment by donal-s** [comment]
> Only one question I presume the logic for not rendering missing fields was already in place?

There's an if statement at the bottom on DataDefinitions.ts

**Comment by scottclarke61** [comment]
I've tested it and it works including only showing the "- [location]" if the field is not missing

**Review by scottclarke61 — APPROVED** [review]

**Comment by byronn-1** [comment]
Looks good. All test suites are passing. Thanks for including me.

**Review by byronn-1 — APPROVED** [review]

**Pull request merged**
